"""empty message

Revision ID: 255e87242074
Revises: 0412bb8696f6
Create Date: 2020-07-22 04:46:14.444895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255e87242074'
down_revision = '0412bb8696f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'facebook_link',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
