"""empty message

Revision ID: 3149993a4aa6
Revises: 2ffb49a9308b
Create Date: 2020-07-21 20:32:03.459216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3149993a4aa6'
down_revision = '2ffb49a9308b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
